# Generated by Django 4.2.9 on 2026-03-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTopology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Network Topologies',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('hub', 'Hub'), ('endpoint', 'Endpoint'), ('repeater', 'Repeater'), ('firewall', 'Firewall'), ('server', 'Server'), ('access_point', 'Access Point'), ('gateway', 'Gateway'), ('load_balancer', 'Load Balancer')], default='router', max_length=20)),
                ('x_pos', models.FloatField(default=300)),
                ('y_pos', models.FloatField(default=300)),
                ('capacity', models.FloatField(default=1000, help_text='Throughput capacity in Mbps')),
                ('processing_delay', models.FloatField(default=1, help_text='Processing delay in ms')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('degraded', 'Degraded'), ('failed', 'Failed')], default='active', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='network.networktopology')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('fiber', 'Fiber Optic'), ('ethernet', 'Ethernet'), ('wifi', 'Wi-Fi'), ('coaxial', 'Coaxial'), ('microwave', 'Microwave'), ('satellite', 'Satellite')], default='ethernet', max_length=20)),
                ('bandwidth', models.FloatField(default=1000, help_text='Bandwidth in Mbps')),
                ('latency', models.FloatField(default=1, help_text='Latency in ms')),
                ('reliability', models.FloatField(default=99.9, help_text='Reliability percentage (0-100)')),
                ('distance', models.FloatField(default=100, help_text='Distance in meters')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='network.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='network.node')),
                ('topology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='network.networktopology')),
            ],
            options={
                'ordering': ['source__name', 'target__name'],
            },
        ),
    ]
