# Generated by Django 4.2.9 on 2026-03-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('results_data', models.JSONField(default=dict)),
                ('risk_score', models.FloatField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('ruleset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='rules.ruleset')),
                ('topology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='network.networktopology')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
