# Generated by Django 4.2.9 on 2026-03-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('max_latency', 'Maximum Link Latency'), ('min_bandwidth', 'Minimum Link Bandwidth'), ('min_reliability', 'Minimum Link Reliability'), ('max_distance', 'Maximum Link Distance'), ('min_redundancy', 'Minimum Redundant Paths'), ('max_connections', 'Maximum Node Connections'), ('min_connections', 'Minimum Node Connections'), ('max_hop_count', 'Maximum Hop Count'), ('max_node_load', 'Maximum Node Load Factor'), ('min_path_diversity', 'Minimum Path Diversity'), ('critical_backup', 'Critical Nodes Require Backup'), ('max_single_bandwidth', 'Maximum Single Connection Bandwidth')], max_length=50)),
                ('threshold', models.FloatField(help_text='Numeric threshold value for this rule')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rules.ruleset')),
            ],
            options={
                'ordering': ['-severity', 'name'],
            },
        ),
    ]
